/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksUseDebounceRouteImport } from './routes/hooks/use-debounce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseDebounceRoute = HooksUseDebounceRouteImport.update({
  id: '/hooks/use-debounce',
  path: '/hooks/use-debounce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hooks/use-debounce'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hooks/use-debounce'
  id: '__root__' | '/' | '/hooks/use-debounce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HooksUseDebounceRoute: typeof HooksUseDebounceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-debounce': {
      id: '/hooks/use-debounce'
      path: '/hooks/use-debounce'
      fullPath: '/hooks/use-debounce'
      preLoaderRoute: typeof HooksUseDebounceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HooksUseDebounceRoute: HooksUseDebounceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
