/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksUseTimeoutRouteImport } from './routes/hooks/use-timeout'
import { Route as HooksUseStorageStateRouteImport } from './routes/hooks/use-storage-state'
import { Route as HooksUseIntervalRouteImport } from './routes/hooks/use-interval'
import { Route as HooksUseDebounceRouteImport } from './routes/hooks/use-debounce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseTimeoutRoute = HooksUseTimeoutRouteImport.update({
  id: '/hooks/use-timeout',
  path: '/hooks/use-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseStorageStateRoute = HooksUseStorageStateRouteImport.update({
  id: '/hooks/use-storage-state',
  path: '/hooks/use-storage-state',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseIntervalRoute = HooksUseIntervalRouteImport.update({
  id: '/hooks/use-interval',
  path: '/hooks/use-interval',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseDebounceRoute = HooksUseDebounceRouteImport.update({
  id: '/hooks/use-debounce',
  path: '/hooks/use-debounce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
  '/hooks/use-interval': typeof HooksUseIntervalRoute
  '/hooks/use-storage-state': typeof HooksUseStorageStateRoute
  '/hooks/use-timeout': typeof HooksUseTimeoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
  '/hooks/use-interval': typeof HooksUseIntervalRoute
  '/hooks/use-storage-state': typeof HooksUseStorageStateRoute
  '/hooks/use-timeout': typeof HooksUseTimeoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hooks/use-debounce': typeof HooksUseDebounceRoute
  '/hooks/use-interval': typeof HooksUseIntervalRoute
  '/hooks/use-storage-state': typeof HooksUseStorageStateRoute
  '/hooks/use-timeout': typeof HooksUseTimeoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hooks/use-debounce'
    | '/hooks/use-interval'
    | '/hooks/use-storage-state'
    | '/hooks/use-timeout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hooks/use-debounce'
    | '/hooks/use-interval'
    | '/hooks/use-storage-state'
    | '/hooks/use-timeout'
  id:
    | '__root__'
    | '/'
    | '/hooks/use-debounce'
    | '/hooks/use-interval'
    | '/hooks/use-storage-state'
    | '/hooks/use-timeout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HooksUseDebounceRoute: typeof HooksUseDebounceRoute
  HooksUseIntervalRoute: typeof HooksUseIntervalRoute
  HooksUseStorageStateRoute: typeof HooksUseStorageStateRoute
  HooksUseTimeoutRoute: typeof HooksUseTimeoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-timeout': {
      id: '/hooks/use-timeout'
      path: '/hooks/use-timeout'
      fullPath: '/hooks/use-timeout'
      preLoaderRoute: typeof HooksUseTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-storage-state': {
      id: '/hooks/use-storage-state'
      path: '/hooks/use-storage-state'
      fullPath: '/hooks/use-storage-state'
      preLoaderRoute: typeof HooksUseStorageStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-interval': {
      id: '/hooks/use-interval'
      path: '/hooks/use-interval'
      fullPath: '/hooks/use-interval'
      preLoaderRoute: typeof HooksUseIntervalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-debounce': {
      id: '/hooks/use-debounce'
      path: '/hooks/use-debounce'
      fullPath: '/hooks/use-debounce'
      preLoaderRoute: typeof HooksUseDebounceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HooksUseDebounceRoute: HooksUseDebounceRoute,
  HooksUseIntervalRoute: HooksUseIntervalRoute,
  HooksUseStorageStateRoute: HooksUseStorageStateRoute,
  HooksUseTimeoutRoute: HooksUseTimeoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
